{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "christmas-community.fullname" . }}-pv
  labels:
    {{- include "christmas-community.labels" . | nindent 4 }}
spec:
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{- toYaml .Values.persistence.mountPath | indent 8}}
  volumeMode: Filesystem
{{- end }}